version: '3'
services:
  app:
    build:
      context: .

    volumes:
      - ./docker/config/opt/docker/etc/php/php.ini:/opt/docker/etc/php/php.ini

    # Entrypoint to run unit test
    entrypoint: vendor/bin/phpunit
